# Generated by Django 4.2 on 2023-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gonder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(max_length=120)),
                ('yazi', models.CharField(max_length=90000)),
            ],
        ),
    ]
