# Generated by Django 4.2 on 2023-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonder',
            name='baslik',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='gonder',
            name='yazi',
            field=models.TextField(max_length=90000),
        ),
    ]
