# Generated by Django 4.2 on 2023-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_gonder_baslik_alter_gonder_yazi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
