# Generated by Django 4.2 on 2023-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_gonder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gonder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
