# Generated by Django 4.2 on 2023-06-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_remove_anahaber_image_alter_anahaber_baslik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anahaber',
            name='baslik',
            field=models.CharField(max_length=120),
        ),
    ]
