# Generated by Django 4.2 on 2023-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='anahaber',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
