# Generated by Django 4.2 on 2023-06-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_anahaber_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anahaber',
            name='image',
            field=models.ImageField(null=True, upload_to='Haber-Resimler/'),
        ),
    ]
