# Generated by Django 4.2 on 2023-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_anahaber_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_Ekle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
    ]
