# Generated by Django 4.2 on 2023-06-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_anahaber_kategoriler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu_basligi', models.CharField(max_length=100)),
                ('konu', models.TextField()),
                ('e_posta', models.EmailField(max_length=254)),
            ],
        ),
    ]
