# Generated by Django 4.2 on 2023-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_resmi', models.ImageField(upload_to='urunler/')),
                ('urun_ismi', models.CharField(max_length=100)),
                ('urun_aciklamasi', models.TextField()),
                ('urun_fiyati', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stok_adedi', models.PositiveIntegerField()),
            ],
        ),
    ]
