# Generated by Django 4.2 on 2023-06-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0020_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profil_foto',
            field=models.ImageField(blank=True, upload_to='profil_fotolari/'),
        ),
    ]
