# Generated by Django 4.2 on 2023-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0021_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profil_foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
