# Generated by Django 4.2 on 2023-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0024_customuser_bio_customuser_profil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profil_foto',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profil_foto',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
