# Generated by Django 4.2 on 2023-06-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0025_remove_customuser_bio_remove_customuser_profil_foto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
