# Generated by Django 4.2 on 2023-06-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0028_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
