# Generated by Django 4.2 on 2023-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0029_remove_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
