# Generated by Django 4.2 on 2023-06-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0031_category_remove_anahaber_kategoriler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderi', to='BlogApp.category')),
            ],
        ),
    ]
