# Generated by Django 4.2 on 2023-06-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0032_gonderi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
