# Generated by Django 4.2 on 2023-06-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0035_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
