# Generated by Django 4.2 on 2023-06-26 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0036_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='anahaber',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
