# Generated by Django 4.2 on 2023-06-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0038_rename_tarih_anahaber_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anahaber',
            name='Kategoriler',
            field=models.ManyToManyField(to='BlogApp.category'),
        ),
    ]
