# Generated by Django 4.2 on 2023-06-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0039_anahaber_kategoriler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anahaber',
            name='Kategoriler',
        ),
    ]
